//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMSMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int LeaveRequestID { get; set; }
        public Nullable<int> LeaveType { get; set; }
        public int NoOfDays { get; set; }
        public int LeaveBalance { get; set; }
        public System.DateTime LeaveDateFrom { get; set; }
        public System.DateTime LeaveDateTo { get; set; }
        public int LeaveStatus { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual LeaveType LeaveType1 { get; set; }
        public virtual Status Status { get; set; }
    }
}
